import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useAppSelector } from 'src/app/hooks';
import { PostContainer } from 'src/features/posts/components/PostContainer';

const Home: NextPage = () => {
  const router = useRouter();
  const signinState = useAppSelector((state) => state.auth.signin);

  if (!signinState.accessToken) {
    //ログイン済みの場合は、認証後のメインページに飛ばす
    router.push('/signin');
    return <></>;
  }

  return (
    <div>
      <Head>
        <title>トップページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>トップページ</h1>
      <PostContainer />
    </div>
  );
};

export default Home;
