version: '3.8'
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: develop
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data