import type { NextPage } from 'next';
import Head from 'next/head';
import { SignupForm } from 'src/features/auth/components/signup/SignupForm';

const SignupPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>新規登録</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignupForm />
    </div>
  );
};

export default SignupPage;
