import type { NextPage } from 'next';
import Head from 'next/head';
import { SigninForm } from 'src/features/auth/components/signin/SigninForm';

const SignupPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SigninForm />
    </div>
  );
};

export default SignupPage;
